
<img src="Youth unemployment concept banner .jpg" width="1200" height="400">

# Youth Unemployment Data Visualization Lab Project

&#10147;  M.Muaz Abdullah (23i-5237)


&#10147;  Aleena Zahra (23i-2514)


&#10147;  Abdullah Bin Asim (23i-2621)


&#10147;  Sheharyar Bhatti (21i-2670)

## Table of Contents

1. [**Introduction**](#1)
    - Project Description
    - Data Description
2. [**Acquiring and Loading Data**](#2)
	- Importing Libraries and Notebook Setup
    - Loading Data
    - Basic Data Exploration
    - Areas to Fix
3. [**Data Proprocessing**](#3)
4. [**Data Analysis**](#4)
5. [**Conclusion**](#5)
    - Insights
    - Suggestions
    - Possible Next Steps
6. [**Epilogue**](#6) 
    - References
    - Versioning

---

# 1

## Introduction

Youth unemployment refers to young people aged 15–24 who are actively seeking employment but are unable to find jobs. In developing countries, this issue is particularly acute due to a large youth population entering the labor market annually. Globally, more than 64 million young people are unemployed, with the majority residing in developing nations where 90% of youth live (WDI, 2024).

&#10144; Youth unemployment has serious economic and social consequences:

&#10144; Lower consumer spending and tax revenues, increased fiscal burdens

&#10144; Poverty, psychological distress, crime, and potential political instability

&#10144; Brain drain as skilled youth emigrate for better opportunities

&#10144; Addressing youth unemployment is crucial for economic growth, innovation, and social stability.


### Project Description


**Goal/Purpose:** 

The primary goal of this analysis is to understand the determinants of youth unemployment in developing countries and identify patterns that may help policymakers improve employment opportunities for young people.

<p>&nbsp;</p>

**Key Questions to be Answered:**

1. How do youth unemployment rates vary across countries and regions?

2. What is the relationship between education levels and youth unemployment?

3. How does government expenditure on education correlate with youth employment?

4. Are there trends or patterns over the period 2010–2022 that indicate improvement or worsening of youth unemployment?

5. What insights can be drawn specifically from the case study of Pakistan?

<p>&nbsp;</p>

**Assumptions/Methodology/Scope:** 

*Exploratory Data Analysis (EDA):*
Examine distributions, correlations, and missing values

*Data Preprocessing:*

Fix column names, data types, and categorical variables

Handle missing values with linear interpolation and medians

Drop duplicates and irrelevant or redundant columns

*Assumptions:*

Education and government expenditure are proxies for youth skill development

GDP per capita is a proxy for economic opportunities

Trends in the dataset reflect broader national patterns

<p>&nbsp;</p>


### Data Description

**Content:** 

This dataset is a excel file sourced from the *World Development Indicators (WDI)* and covers 2010–2022 for developing countries across Africa, Asia, Latin America, the Middle East, and North Africa. The key variables include:

<p>&nbsp;</p>

**Description of Attributes:** 

Here you can describe what each column represents.

| Column | Description |
| :------ | :---------- |
| `country` | Country name |
| `country_code` | ISO country code |
| `year` | Year (2010–2022) |
| `unemp_adv_edu` | Unemployment with advanced education (% of labor force with advanced education) |
| `unemp_basic_edu` | Unemployment with basic education (% of labor force with basic education) |
| `unemp_intermediate_edu` | Unemployment with intermediate education (% of labor force with intermediate education) |
| `unemployment_total` | Total unemployment (% of total labor force) |
| `unemp_youth_total` | Youth unemployment (% of youth labor force ages 15–24) |
| `exp_primary` | Current education expenditure: primary (% of public education spending) |
| `exp_secondary` | Current education expenditure: secondary (% of public education spending) |
| `exp_tertiary` | Current education expenditure: tertiary (% of public education spending) |
| `exp_total` | Education expenditure: total (% of public institutions) |
| `attain_bachelors` | Population 25+ with at least a Bachelor's degree (%) |
| `attain_lower_secondary` | Population 25+ with at least completed lower secondary education (%) |
| `attain_post_secondary` | Population 25+ with at least completed post-secondary education (%) |
| `attain_primary` | Population 25+ with at least completed primary education (%) |
| `attain_short_tertiary` | Population 25+ with short-cycle tertiary education (%) |
| `attain_upper_secondary` | Population 25+ with completed upper secondary education (%) |
| `attain_masters` | Population 25+ with at least a Master's degree (%) |
| `attain_doctoral` | Population 25+ with a doctoral degree (%) |
| `gov_exp_primary` | Government expenditure on primary education (% of government education spending) |
| `gov_exp_secondary` | Government expenditure on secondary education (% of government education spending) |
| `gov_exp_tertiary` | Government expenditure on tertiary education (% of government education spending) |
| `gov_exp_total_gdp` | Government expenditure on education (% of GDP) |
| `gov_exp_total_govt` | Government expenditure on education (% of total government expenditure) |
| `gross_intake_primary` | Gross intake ratio in first grade of primary education (%) |
| `labor_adv_edu` | Labor force with advanced education (% of working-age population) |
| `labor_basic_edu` | Labor force with basic education (% of working-age population) |
| `labor_intermediate_edu` | Labor force with intermediate education (% of working-age population) |
| `neet_youth` | Youth not in education, employment, or training (%) |
 

<p>&nbsp;</p>


**Acknowledgements:** 

This dataset is downloaded from the *World Development Indicators (WDI)* website and the original source can be found on [website](https://databank.worldbank.org/source/world-development-indicators).

---

# 2

## Acquiring and Loading Data
### Importing Libraries and Notebook Setup

In [69]:
# Data manipulation
import datetime
import numpy as np
import pandas as pd
import pandas.api.types as ptypes
from skimpy import skim, clean_columns
import re

from sklearn.preprocessing import StandardScaler

# Visualizations
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

# Pandas settings


pd.options.display.float_format = '{:,.3f}'.format
pd.set_option("display.max_columns", None)
# Visualization settings
from matplotlib import rcParams
plt.style.use('fivethirtyeight')
rcParams['figure.figsize'] = (16, 5)   
rcParams['axes.spines.right'] = False
rcParams['axes.spines.top'] = False
rcParams['font.size'] = 12
# rcParams['figure.dpi'] = 300
rcParams['savefig.dpi'] = 300
plt.rc('xtick', labelsize=11)
plt.rc('ytick', labelsize=11)
# Light green pastel theme
custom_palette = ['#b7e4c7', "#47966a", '#74c69d', "#2e7c58", '#40916c', "#18573a"]
custom_hue = ["#e8ffeb", '#b7e4c7', '#95d5b2', '#74c69d', '#52b788', '#40916c']
custom_divergent = ['#d8f3dc', '#a3d9a5', '#74c69d', '#f1f1f1', "#d6e499", "#c2d66a", "#b4ca34"]

sns.set_palette(custom_palette)
%config InlineBackend.figure_format = 'retina'

### Loading Data

In [70]:
# Load DataFrame
df = pd.read_excel("file.xlsx")

## Basic Data Exploration

### Show Shape of Data Frame

In [27]:
# Show rows and columns count
print(f"Rows count: {df.shape[0]}\nColumns count: {df.shape[1]}")

Rows count: 2665
Columns count: 31

### Show Names of all Columns

In [31]:

print(df.columns.tolist())

['country_name', 'country_code', 'time', 'time_code', 'unemployment_with_advanced_education_%_of_total_labor_force_with_advanced_education_sl_uem_advn_zs', 'unemployment_with_basic_education_%_of_total_labor_force_with_basic_education_sl_uem_basc_zs', 'unemployment_with_intermediate_education_%_of_total_labor_force_with_intermediate_education_sl_uem_intm_zs', 'unemployment_total_%_of_total_labor_force_modeled_ilo_estimate_sl_uem_totl_zs', 'unemployment_youth_total_%_of_total_labor_force_ages_15_24_modeled_ilo_estimate_sl_uem_1524_zs', 'current_education_expenditure_primary_%_of_total_expenditure_in_primary_public_institutions_se_xpd_cprm_zs', 'current_education_expenditure_secondary_%_of_total_expenditure_in_secondary_public_institutions_se_xpd_csec_zs', 'current_education_expenditure_tertiary_%_of_total_expenditure_in_tertiary_public_institutions_se_xpd_cter_zs', 'current_education_expenditure_total_%_of_total_expenditure_in_public_institutions_se_xpd_ctot_zs', 'educational_attainment_at_least_bachelors_or_equivalent_population_25_total_%_cumulative_se_ter_cuat_ba_zs', 'educational_attainment_at_least_completed_lower_secondary_population_25_total_%_cumulative_se_sec_cuat_lo_zs', 'educational_attainment_at_least_completed_post_secondary_population_25_total_%_cumulative_se_sec_cuat_po_zs', 'educational_attainment_at_least_completed_primary_population_25_years_total_%_cumulative_se_prm_cuat_zs', 'educational_attainment_at_least_completed_short_cycle_tertiary_population_25_total_%_cumulative_se_ter_cuat_st_zs', 'educational_attainment_at_least_completed_upper_secondary_population_25_total_%_cumulative_se_sec_cuat_up_zs', 'educational_attainment_at_least_masters_or_equivalent_population_25_total_%_cumulative_se_ter_cuat_ms_zs', 'educational_attainment_doctoral_or_equivalent_population_25_total_%_cumulative_se_ter_cuat_do_zs', 'expenditure_on_primary_education_%_of_government_expenditure_on_education_se_xpd_prim_zs', 'expenditure_on_secondary_education_%_of_government_expenditure_on_education_se_xpd_seco_zs', 'expenditure_on_tertiary_education_%_of_government_expenditure_on_education_se_xpd_tert_zs', 'government_expenditure_on_education_total_%_of_gdp_se_xpd_totl_gd_zs', 'government_expenditure_on_education_total_%_of_government_expenditure_se_xpd_totl_gb_zs', 'gross_intake_ratio_in_first_grade_of_primary_education_total_%_of_relevant_age_group_se_prm_gint_zs', 'labor_force_with_advanced_education_%_of_total_working_age_population_with_advanced_education_sl_tlf_advn_zs', 'labor_force_with_basic_education_%_of_total_working_age_population_with_basic_education_sl_tlf_basc_zs', 'labor_force_with_intermediate_education_%_of_total_working_age_population_with_intermediate_education_sl_tlf_intm_zs', 'share_of_youth_not_in_education_employment_or_training_total_%_of_youth_population_sl_uem_neet_zs']

#### Explore Head and Tail

In [ ]:
df.head()

In [ ]:
df.tail()

#### Check Data Types

In [ ]:
# Show data types
df.info()

#### Check Missing Data

In [8]:
# Print percentage of missing values
missing_percent = df.isna().mean().sort_values(ascending=False)
print('---- Percentage of Missing Values (%) -----')
if missing_percent.sum():
    print(missing_percent[missing_percent > 0] * 100)
else:
    print('None')

---- Percentage of Missing Values (%) -----
Expenditure on primary education (% of government expenditure on education) [SE.XPD.PRIM.ZS]                                                90.694
Expenditure on secondary education (% of government expenditure on education) [SE.XPD.SECO.ZS]                                              90.507
Expenditure on tertiary education (% of government expenditure on education) [SE.XPD.TERT.ZS]                                               89.681
Educational attainment, Doctoral or equivalent, population 25+, female (%) (cumulative) [SE.TER.CUAT.DO.FE.ZS]                              80.113
Educational attainment, Doctoral or equivalent, population 25+, male (%) (cumulative) [SE.TER.CUAT.DO.MA.ZS]                                78.424
                                                                                                                                             ...
Share of youth not in education, employment or training, male (% of male youth population)  (modeled ILO estimate) [SL.UEM.NEET.MA.ME.ZS]   12.008
Country Code                                                                                                                                 0.188
Time                                                                                                                                         0.188
Time Code                                                                                                                                    0.188
Country Name                                                                                                                                 0.113
Length: 67, dtype: float64

#### Check for Duplicate Rows

In [9]:
# Show number of duplicated rows
print(f"No. of entirely duplicated rows: {df.duplicated().sum()}")

# Show duplicated rows
df[df.duplicated()]

No. of entirely duplicated rows: 2

,Country Name,Country Code,Time,Time Code,Unemployment with advanced education (% of total labor force with advanced education) [SL.UEM.ADVN.ZS],"Unemployment with advanced education, female (% of female labor force with advanced education) [SL.UEM.ADVN.FE.ZS]","Unemployment with advanced education, male (% of male labor force with advanced education) [SL.UEM.ADVN.MA.ZS]",Unemployment with basic education (% of total labor force with basic education) [SL.UEM.BASC.ZS],"Unemployment with basic education, female (% of female labor force with basic education) [SL.UEM.BASC.FE.ZS]","Unemployment with basic education, male (% of male labor force with basic education) [SL.UEM.BASC.MA.ZS]","Unemployment with intermediate education, female (% of female labor force with intermediate education) [SL.UEM.INTM.FE.ZS]","Unemployment with intermediate education, male (% of male labor force with intermediate education) [SL.UEM.INTM.MA.ZS]",Unemployment with intermediate education (% of total labor force with intermediate education) [SL.UEM.INTM.ZS],"Unemployment, female (% of female labor force) (modeled ILO estimate) [SL.UEM.TOTL.FE.ZS]","Unemployment, male (% of male labor force) (modeled ILO estimate) [SL.UEM.TOTL.MA.ZS]","Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]","Unemployment, youth female (% of female labor force ages 15-24) (modeled ILO estimate) [SL.UEM.1524.FE.ZS]","Unemployment, youth male (% of male labor force ages 15-24) (modeled ILO estimate) [SL.UEM.1524.MA.ZS]","Unemployment, youth total (% of total labor force ages 15-24) (modeled ILO estimate) [SL.UEM.1524.ZS]","Current education expenditure, primary (% of total expenditure in primary public institutions) [SE.XPD.CPRM.ZS]","Current education expenditure, secondary (% of total expenditure in secondary public institutions) [SE.XPD.CSEC.ZS]","Current education expenditure, tertiary (% of total expenditure in tertiary public institutions) [SE.XPD.CTER.ZS]","Current education expenditure, total (% of total expenditure in public institutions) [SE.XPD.CTOT.ZS]","Educational attainment, at least Bachelor's or equivalent, population 25+, female (%) (cumulative) [SE.TER.CUAT.BA.FE.ZS]","Educational attainment, at least Bachelor's or equivalent, population 25+, male (%) (cumulative) [SE.TER.CUAT.BA.MA.ZS]","Educational attainment, at least Bachelor's or equivalent, population 25+, total (%) (cumulative) [SE.TER.CUAT.BA.ZS]","Educational attainment, at least completed lower secondary, population 25+, female (%) (cumulative) [SE.SEC.CUAT.LO.FE.ZS]","Educational attainment, at least completed lower secondary, population 25+, male (%) (cumulative) [SE.SEC.CUAT.LO.MA.ZS]","Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative) [SE.SEC.CUAT.LO.ZS]","Educational attainment, at least completed post-secondary, population 25+, female (%) (cumulative) [SE.SEC.CUAT.PO.FE.ZS]","Educational attainment, at least completed post-secondary, population 25+, male (%) (cumulative) [SE.SEC.CUAT.PO.MA.ZS]","Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative) [SE.SEC.CUAT.PO.ZS]","Educational attainment, at least completed primary, population 25+ years, female (%) (cumulative) [SE.PRM.CUAT.FE.ZS]","Educational attainment, at least completed primary, population 25+ years, male (%) (cumulative) [SE.PRM.CUAT.MA.ZS]","Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative) [SE.PRM.CUAT.ZS]","Educational attainment, at least completed short-cycle tertiary, population 25+, female (%) (cumulative) [SE.TER.CUAT.ST.FE.ZS]","Educational attainment, at least completed short-cycle tertiary, population 25+, male (%) (cumulative) [SE.TER.CUAT.ST.MA.ZS]","Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative) [SE.TER.CUAT.ST.ZS]","Educational attainment, at least completed upper secondary, population 25+, female (%) (cumulative) [SE.SEC.CUAT.UP.FE.ZS]","Educational attainment, at least completed upper secondary, population 25+, male (%) (cumulative) [SE.SEC.CUAT.UP.MA.ZS]","Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative) [SE.SEC.CUAT.UP.ZS]","Educational attainment, at least Master's or equivalent, population 25+, female (%) (cumulative) [SE.TER.CUAT.MS.FE.ZS]","Educational attainment, at least Master's or equivalent, population 25+, male (%) (cumulative) [SE.TER.CUAT.MS.MA.ZS]","Educational attainment, at least Master's or equivalent, population 25+, total (%) (cumulative) [SE.TER.CUAT.MS.ZS]","Educational attainment, Doctoral or equivalent, population 25+, female (%) (cumulative) [SE.TER.CUAT.DO.FE.ZS]","Educational attainment, Doctoral or equivalent, population 25+, male (%) (cumulative) [SE.TER.CUAT.DO.MA.ZS]","Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative) [SE.TER.CUAT.DO.ZS]",Expenditure on primary education (% of government expenditure on education) [SE.XPD.PRIM.ZS],Expenditure on secondary education (% of government expenditure on education) [SE.XPD.SECO.ZS],Expenditure on tertiary education (% of government expenditure on education) [SE.XPD.TERT.ZS],"Government expenditure on education, total (% of GDP) [SE.XPD.TOTL.GD.ZS]","Government expenditure on education, total (% of government expenditure) [SE.XPD.TOTL.GB.ZS]","Gross intake ratio in first grade of primary education, female (% of relevant age group) [SE.PRM.GINT.FE.ZS]","Gross intake ratio in first grade of primary education, male (% of relevant age group) [SE.PRM.GINT.MA.ZS]","Gross intake ratio in first grade of primary education, total (% of relevant age group) [SE.PRM.GINT.ZS]",Labor force with advanced education (% of total working-age population with advanced education) [SL.TLF.ADVN.ZS],"Labor force with advanced education, female (% of female working-age population with advanced education) [SL.TLF.ADVN.FE.ZS]","Labor force with advanced education, male (% of male working-age population with advanced education) [SL.TLF.ADVN.MA.ZS]",Labor force with basic education (% of total working-age population with basic education) [SL.TLF.BASC.ZS],"Labor force with basic education, female (% of female working-age population with basic education) [SL.TLF.BASC.FE.ZS]","Labor force with basic education, male (% of male working-age population with basic education) [SL.TLF.BASC.MA.ZS]",Labor force with intermediate education (% of total working-age population with intermediate education) [SL.TLF.INTM.ZS],"Labor force with intermediate education, female (% of female working-age population with intermediate education) [SL.TLF.INTM.FE.ZS]","Labor force with intermediate education, male (% of male working-age population with intermediate education) [SL.TLF.INTM.MA.ZS]","Share of youth not in education, employment or training, total (% of youth population) [SL.UEM.NEET.ZS]","Share of youth not in education, employment or training, male (% of male youth population) (modeled ILO estimate) [SL.UEM.NEET.MA.ME.ZS]","Share of youth not in education, employment or training, female (% of female youth population) (modeled ILO estimate) [SL.UEM.NEET.FE.ME.ZS]"
2661,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2662,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Check Uniqueness of Data

In [ ]:
# Print the percentage similarity of values (the lower %, the better)
num_unique = df.nunique().sort_values()
print('---- Percentage Similarity of Values (%) -----')
print(100/num_unique)

#### Check Data Range

In [ ]:
# Print summary statistics
df.describe(include='all')
skim(df)

#### Check Frequency of Mode

In [ ]:
# Check the proportion of the most frequent value in each column
print('---- Frequency of the Mode (%) -----')
mode_dict = {col: (df[col].value_counts().iat[0] / df[col].size * 100) for col in df.columns}
mode_series = pd.Series(mode_dict)
mode_series.sort_values(ascending=False)

In [ ]:
# Show the value frequency of each column greater than the mode's threshold
threshold = 80
for col in mode_series[mode_series > threshold].index:
    print(df[col].value_counts(dropna=False))

In [76]:
df.describe(include='all')

,Country Name,Country Code,Time,Time Code,Unemployment with advanced education (% of total labor force with advanced education) [SL.UEM.ADVN.ZS],"Unemployment with advanced education, female (% of female labor force with advanced education) [SL.UEM.ADVN.FE.ZS]","Unemployment with advanced education, male (% of male labor force with advanced education) [SL.UEM.ADVN.MA.ZS]",Unemployment with basic education (% of total labor force with basic education) [SL.UEM.BASC.ZS],"Unemployment with basic education, female (% of female labor force with basic education) [SL.UEM.BASC.FE.ZS]","Unemployment with basic education, male (% of male labor force with basic education) [SL.UEM.BASC.MA.ZS]","Unemployment with intermediate education, female (% of female labor force with intermediate education) [SL.UEM.INTM.FE.ZS]","Unemployment with intermediate education, male (% of male labor force with intermediate education) [SL.UEM.INTM.MA.ZS]",Unemployment with intermediate education (% of total labor force with intermediate education) [SL.UEM.INTM.ZS],"Unemployment, female (% of female labor force) (modeled ILO estimate) [SL.UEM.TOTL.FE.ZS]","Unemployment, male (% of male labor force) (modeled ILO estimate) [SL.UEM.TOTL.MA.ZS]","Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]","Unemployment, youth female (% of female labor force ages 15-24) (modeled ILO estimate) [SL.UEM.1524.FE.ZS]","Unemployment, youth male (% of male labor force ages 15-24) (modeled ILO estimate) [SL.UEM.1524.MA.ZS]","Unemployment, youth total (% of total labor force ages 15-24) (modeled ILO estimate) [SL.UEM.1524.ZS]","Current education expenditure, primary (% of total expenditure in primary public institutions) [SE.XPD.CPRM.ZS]","Current education expenditure, secondary (% of total expenditure in secondary public institutions) [SE.XPD.CSEC.ZS]","Current education expenditure, tertiary (% of total expenditure in tertiary public institutions) [SE.XPD.CTER.ZS]","Current education expenditure, total (% of total expenditure in public institutions) [SE.XPD.CTOT.ZS]","Educational attainment, at least Bachelor's or equivalent, population 25+, female (%) (cumulative) [SE.TER.CUAT.BA.FE.ZS]","Educational attainment, at least Bachelor's or equivalent, population 25+, male (%) (cumulative) [SE.TER.CUAT.BA.MA.ZS]","Educational attainment, at least Bachelor's or equivalent, population 25+, total (%) (cumulative) [SE.TER.CUAT.BA.ZS]","Educational attainment, at least completed lower secondary, population 25+, female (%) (cumulative) [SE.SEC.CUAT.LO.FE.ZS]","Educational attainment, at least completed lower secondary, population 25+, male (%) (cumulative) [SE.SEC.CUAT.LO.MA.ZS]","Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative) [SE.SEC.CUAT.LO.ZS]","Educational attainment, at least completed post-secondary, population 25+, female (%) (cumulative) [SE.SEC.CUAT.PO.FE.ZS]","Educational attainment, at least completed post-secondary, population 25+, male (%) (cumulative) [SE.SEC.CUAT.PO.MA.ZS]","Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative) [SE.SEC.CUAT.PO.ZS]","Educational attainment, at least completed primary, population 25+ years, female (%) (cumulative) [SE.PRM.CUAT.FE.ZS]","Educational attainment, at least completed primary, population 25+ years, male (%) (cumulative) [SE.PRM.CUAT.MA.ZS]","Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative) [SE.PRM.CUAT.ZS]","Educational attainment, at least completed short-cycle tertiary, population 25+, female (%) (cumulative) [SE.TER.CUAT.ST.FE.ZS]","Educational attainment, at least completed short-cycle tertiary, population 25+, male (%) (cumulative) [SE.TER.CUAT.ST.MA.ZS]","Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative) [SE.TER.CUAT.ST.ZS]","Educational attainment, at least completed upper secondary, population 25+, female (%) (cumulative) [SE.SEC.CUAT.UP.FE.ZS]","Educational attainment, at least completed upper secondary, population 25+, male (%) (cumulative) [SE.SEC.CUAT.UP.MA.ZS]","Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative) [SE.SEC.CUAT.UP.ZS]","Educational attainment, at least Master's or equivalent, population 25+, female (%) (cumulative) [SE.TER.CUAT.MS.FE.ZS]","Educational attainment, at least Master's or equivalent, population 25+, male (%) (cumulative) [SE.TER.CUAT.MS.MA.ZS]","Educational attainment, at least Master's or equivalent, population 25+, total (%) (cumulative) [SE.TER.CUAT.MS.ZS]","Educational attainment, Doctoral or equivalent, population 25+, female (%) (cumulative) [SE.TER.CUAT.DO.FE.ZS]","Educational attainment, Doctoral or equivalent, population 25+, male (%) (cumulative) [SE.TER.CUAT.DO.MA.ZS]","Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative) [SE.TER.CUAT.DO.ZS]",Expenditure on primary education (% of government expenditure on education) [SE.XPD.PRIM.ZS],Expenditure on secondary education (% of government expenditure on education) [SE.XPD.SECO.ZS],Expenditure on tertiary education (% of government expenditure on education) [SE.XPD.TERT.ZS],"Government expenditure on education, total (% of GDP) [SE.XPD.TOTL.GD.ZS]","Government expenditure on education, total (% of government expenditure) [SE.XPD.TOTL.GB.ZS]","Gross intake ratio in first grade of primary education, female (% of relevant age group) [SE.PRM.GINT.FE.ZS]","Gross intake ratio in first grade of primary education, male (% of relevant age group) [SE.PRM.GINT.MA.ZS]","Gross intake ratio in first grade of primary education, total (% of relevant age group) [SE.PRM.GINT.ZS]",Labor force with advanced education (% of total working-age population with advanced education) [SL.TLF.ADVN.ZS],"Labor force with advanced education, female (% of female working-age population with advanced education) [SL.TLF.ADVN.FE.ZS]","Labor force with advanced education, male (% of male working-age population with advanced education) [SL.TLF.ADVN.MA.ZS]",Labor force with basic education (% of total working-age population with basic education) [SL.TLF.BASC.ZS],"Labor force with basic education, female (% of female working-age population with basic education) [SL.TLF.BASC.FE.ZS]","Labor force with basic education, male (% of male working-age population with basic education) [SL.TLF.BASC.MA.ZS]",Labor force with intermediate education (% of total working-age population with intermediate education) [SL.TLF.INTM.ZS],"Labor force with intermediate education, female (% of female working-age population with intermediate education) [SL.TLF.INTM.FE.ZS]","Labor force with intermediate education, male (% of male working-age population with intermediate education) [SL.TLF.INTM.MA.ZS]","Share of youth not in education, employment or training, total (% of youth population) [SL.UEM.NEET.ZS]","Share of youth not in education, employment or training, male (% of male youth population) (modeled ILO estimate) [SL.UEM.NEET.MA.ME.ZS]","Share of youth not in education, employment or training, female (% of female youth population) (modeled ILO estimate) [SL.UEM.NEET.FE.ME.ZS]"
count,2662,2660,"2,660.000",2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660,2660
unique,268,266,NaN,10,1143,1160,1139,1176,1169,1174,1168,1153,1176,2211,2209,2178,2296,2280,2273,647,668,680,693,857,848,855,844,848,838,608,603,607,856,848,858,852,854,851,966,974,979,672,692,701,392,454,472,233,238,258,1641,1669,687,688,689,1197,1181,1174,1203,1198,1198,1186,1196,1187,1145,2257,2301
top,World,WLD,NaN,YR2015,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..,..
freq,10,10,NaN,266,1443,1452,1458,1438,1442,1442,1449,1446,1436,319,319,319,319,319,319,1907,1894,1889,1884,1794,1791,1790,1804,1793,1799,2045,2051,2046,1689,1682,1681,1796,1800,1799,1673,1673,1671,1951,1921,1920,2130,2085,2058,2412,2407,2385,782,745,1965,1965,1964,1439,1441,1440,1442,1441,1444,1438,1439,1440,1480,315,315
mean,NaN,NaN,"2,019.500",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,NaN,NaN,2.873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,NaN,NaN,"2,015.000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,NaN,NaN,"2,017.000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,NaN,NaN,"2,019.500",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,NaN,NaN,"2,022.000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,NaN,NaN,"2,024.000",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2665 entries, 0 to 2664
Data columns (total 67 columns):
 #   Column                                                                                                                                        Non-Null Count  Dtype
---  ------                                                                                                                                        --------------  -----
 0   Country Name                                                                                                                                  2662 non-null   object
 1   Country Code                                                                                                                                  2660 non-null   object
 2   Time                                                                                                                                          2660 non-null   float64
 3   Time Code                                                                                                                                     2660 non-null   object
 4   Unemployment with advanced education (% of total labor force with advanced education) [SL.UEM.ADVN.ZS]                                        2660 non-null   object
 5   Unemployment with advanced education, female (% of female labor force with advanced education) [SL.UEM.ADVN.FE.ZS]                            2660 non-null   object
 6   Unemployment with advanced education, male (% of male labor force with advanced education) [SL.UEM.ADVN.MA.ZS]                                2660 non-null   object
 7   Unemployment with basic education (% of total labor force with basic education) [SL.UEM.BASC.ZS]                                              2660 non-null   object
 8   Unemployment with basic education, female (% of female labor force with basic education) [SL.UEM.BASC.FE.ZS]                                  2660 non-null   object
 9   Unemployment with basic education, male (% of male labor force with basic education) [SL.UEM.BASC.MA.ZS]                                      2660 non-null   object
 10  Unemployment with intermediate education, female (% of female labor force with intermediate education) [SL.UEM.INTM.FE.ZS]                    2660 non-null   object
 11  Unemployment with intermediate education, male (% of male labor force with intermediate education) [SL.UEM.INTM.MA.ZS]                        2660 non-null   object
 12  Unemployment with intermediate education (% of total labor force with intermediate education) [SL.UEM.INTM.ZS]                                2660 non-null   object
 13  Unemployment, female (% of female labor force) (modeled ILO estimate) [SL.UEM.TOTL.FE.ZS]                                                     2660 non-null   object
 14  Unemployment, male (% of male labor force) (modeled ILO estimate) [SL.UEM.TOTL.MA.ZS]                                                         2660 non-null   object
 15  Unemployment, total (% of total labor force) (modeled ILO estimate) [SL.UEM.TOTL.ZS]                                                          2660 non-null   object
 16  Unemployment, youth female (% of female labor force ages 15-24) (modeled ILO estimate) [SL.UEM.1524.FE.ZS]                                    2660 non-null   object
 17  Unemployment, youth male (% of male labor force ages 15-24) (modeled ILO estimate) [SL.UEM.1524.MA.ZS]                                        2660 non-null   object
 18  Unemployment, youth total (% of total labor force ages 15-24) (modeled ILO estimate) [SL.UEM.1524.ZS]                                         2660 non-null   object
 19  Current education expenditure, primary (% of total expenditure in primary public institutions) [SE.XPD.CPRM.ZS]                               2660 non-null   object
 20  Current education expenditure, secondary (% of total expenditure in secondary public institutions) [SE.XPD.CSEC.ZS]                           2660 non-null   object
 21  Current education expenditure, tertiary (% of total expenditure in tertiary public institutions) [SE.XPD.CTER.ZS]                             2660 non-null   object
 22  Current education expenditure, total (% of total expenditure in public institutions) [SE.XPD.CTOT.ZS]                                         2660 non-null   object
 23  Educational attainment, at least Bachelor's or equivalent, population 25+, female (%) (cumulative) [SE.TER.CUAT.BA.FE.ZS]                     2660 non-null   object
 24  Educational attainment, at least Bachelor's or equivalent, population 25+, male (%) (cumulative) [SE.TER.CUAT.BA.MA.ZS]                       2660 non-null   object
 25  Educational attainment, at least Bachelor's or equivalent, population 25+, total (%) (cumulative) [SE.TER.CUAT.BA.ZS]                         2660 non-null   object
 26  Educational attainment, at least completed lower secondary, population 25+, female (%) (cumulative) [SE.SEC.CUAT.LO.FE.ZS]                    2660 non-null   object
 27  Educational attainment, at least completed lower secondary, population 25+, male (%) (cumulative) [SE.SEC.CUAT.LO.MA.ZS]                      2660 non-null   object
 28  Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative) [SE.SEC.CUAT.LO.ZS]                        2660 non-null   object
 29  Educational attainment, at least completed post-secondary, population 25+, female (%) (cumulative) [SE.SEC.CUAT.PO.FE.ZS]                     2660 non-null   object
 30  Educational attainment, at least completed post-secondary, population 25+, male (%) (cumulative) [SE.SEC.CUAT.PO.MA.ZS]                       2660 non-null   object
 31  Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative) [SE.SEC.CUAT.PO.ZS]                         2660 non-null   object
 32  Educational attainment, at least completed primary, population 25+ years, female (%) (cumulative) [SE.PRM.CUAT.FE.ZS]                         2660 non-null   object
 33  Educational attainment, at least completed primary, population 25+ years, male (%) (cumulative) [SE.PRM.CUAT.MA.ZS]                           2660 non-null   object
 34  Educational attainment, at least completed primary, population 25+ years, total (%) (cumulative) [SE.PRM.CUAT.ZS]                             2660 non-null   object
 35  Educational attainment, at least completed short-cycle tertiary, population 25+, female (%) (cumulative) [SE.TER.CUAT.ST.FE.ZS]               2660 non-null   object
 36  Educational attainment, at least completed short-cycle tertiary, population 25+, male (%) (cumulative) [SE.TER.CUAT.ST.MA.ZS]                 2660 non-null   object
 37  Educational attainment, at least completed short-cycle tertiary, population 25+, total (%) (cumulative) [SE.TER.CUAT.ST.ZS]                   2660 non-null   object
 38  Educational attainment, at least completed upper secondary, population 25+, female (%) (cumulative) [SE.SEC.CUAT.UP.FE.ZS]                    2660 non-null   object
 39  Educational attainment, at least completed upper secondary, population 25+, male (%) (cumulative) [SE.SEC.CUAT.UP.MA.ZS]                      2660 non-null   object
 40  Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative) [SE.SEC.CUAT.UP.ZS]                        2660 non-null   object
 41  Educational attainment, at least Master's or equivalent, population 25+, female (%) (cumulative) [SE.TER.CUAT.MS.FE.ZS]                       2660 non-null   object
 42  Educational attainment, at least Master's or equivalent, population 25+, male (%) (cumulative) [SE.TER.CUAT.MS.MA.ZS]                         2660 non-null   object
 43  Educational attainment, at least Master's or equivalent, population 25+, total (%) (cumulative) [SE.TER.CUAT.MS.ZS]                           2660 non-null   object
 44  Educational attainment, Doctoral or equivalent, population 25+, female (%) (cumulative) [SE.TER.CUAT.DO.FE.ZS]                                2660 non-null   object
 45  Educational attainment, Doctoral or equivalent, population 25+, male (%) (cumulative) [SE.TER.CUAT.DO.MA.ZS]                                  2660 non-null   object
 46  Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative) [SE.TER.CUAT.DO.ZS]                                    2660 non-null   object
 47  Expenditure on primary education (% of government expenditure on education) [SE.XPD.PRIM.ZS]                                                  2660 non-null   object
 48  Expenditure on secondary education (% of government expenditure on education) [SE.XPD.SECO.ZS]                                                2660 non-null   object
 49  Expenditure on tertiary education (% of government expenditure on education) [SE.XPD.TERT.ZS]                                                 2660 non-null   object
 50  Government expenditure on education, total (% of GDP) [SE.XPD.TOTL.GD.ZS]                                                                     2660 non-null   object
 51  Government expenditure on education, total (% of government expenditure) [SE.XPD.TOTL.GB.ZS]                                                  2660 non-null   object
 52  Gross intake ratio in first grade of primary education, female (% of relevant age group) [SE.PRM.GINT.FE.ZS]                                  2660 non-null   object
 53  Gross intake ratio in first grade of primary education, male (% of relevant age group) [SE.PRM.GINT.MA.ZS]                                    2660 non-null   object
 54  Gross intake ratio in first grade of primary education, total (% of relevant age group) [SE.PRM.GINT.ZS]                                      2660 non-null   object
 55  Labor force with advanced education (% of total working-age population with advanced education) [SL.TLF.ADVN.ZS]                              2660 non-null   object
 56  Labor force with advanced education, female (% of female working-age population with advanced education) [SL.TLF.ADVN.FE.ZS]                  2660 non-null   object
 57  Labor force with advanced education, male (% of male working-age population with advanced education) [SL.TLF.ADVN.MA.ZS]                      2660 non-null   object
 58  Labor force with basic education (% of total working-age population with basic education) [SL.TLF.BASC.ZS]                                    2660 non-null   object
 59  Labor force with basic education, female (% of female working-age population with basic education) [SL.TLF.BASC.FE.ZS]                        2660 non-null   object
 60  Labor force with basic education, male (% of male working-age population with basic education) [SL.TLF.BASC.MA.ZS]                            2660 non-null   object
 61  Labor force with intermediate education (% of total working-age population with intermediate education) [SL.TLF.INTM.ZS]                      2660 non-null   object
 62  Labor force with intermediate education, female (% of female working-age population with intermediate education) [SL.TLF.INTM.FE.ZS]          2660 non-null   object
 63  Labor force with intermediate education, male (% of male working-age population with intermediate education) [SL.TLF.INTM.MA.ZS]              2660 non-null   object
 64  Share of youth not in education, employment or training, total (% of youth population) [SL.UEM.NEET.ZS]                                       2660 non-null   object
 65  Share of youth not in education, employment or training, male (% of male youth population)  (modeled ILO estimate) [SL.UEM.NEET.MA.ME.ZS]     2660 non-null   object
 66  Share of youth not in education, employment or training, female (% of female youth population) (modeled ILO estimate) [SL.UEM.NEET.FE.ME.ZS]  2660 non-null   object
dtypes: float64(1), object(66)
memory usage: 1.4+ MB

In [75]:
df.describe(include='all')
skim(df)

╭──────────────────────────────────────────────── skimpy summary ─────────────────────────────────────────────────╮
│          Data Summary                Data Types                                                                 │
│ ┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┓ ┏━━━━━━━━━━━━━┳━━━━━━━┓                                                          │
│ ┃ Dataframe         ┃ Values ┃ ┃ Column Type ┃ Count ┃                                                          │
│ ┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━┩ ┡━━━━━━━━━━━━━╇━━━━━━━┩                                                          │
│ │ Number of rows    │ 2665   │ │ string      │ 3     │                                                          │
│ │ Number of columns │ 4      │ │ float64     │ 1     │                                                          │
│ └───────────────────┴────────┘ └─────────────┴───────┘                                                          │
│                                                     number                                                      │
│ ┏━━━━━━━━━━┳━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━┳━━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━┳━━━━━━━━┓  │
│ ┃ column   ┃ NA  ┃ NA %                    ┃ mean  ┃ sd     ┃ p0    ┃ p25   ┃ p50   ┃ p75   ┃ p100  ┃ hist   ┃  │
│ ┡━━━━━━━━━━╇━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━╇━━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━╇━━━━━━━━┩  │
│ │ Time     │   5 │     0.18761726078799248 │  2020 │  2.873 │  2015 │  2017 │  2020 │  2022 │  2024 │ ▇▃▇▃▇▇ │  │
│ └──────────┴─────┴─────────────────────────┴───────┴────────┴───────┴───────┴───────┴───────┴───────┴────────┘  │
│                                                     string                                                      │
│ ┏━━━━━━━━━━━┳━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━┓  │
│ ┃           ┃    ┃           ┃          ┃           ┃           ┃          ┃ chars    ┃ words per ┃ total    ┃  │
│ ┃ column    ┃ NA ┃ NA %      ┃ shortest ┃ longest   ┃ min       ┃ max      ┃ per row  ┃ row       ┃ words    ┃  │
│ ┡━━━━━━━━━━━╇━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━┩  │
│ │ Country   │  3 │ 0.1125703 │ Chad     │ Middle    │ Afghanist │ Zimbabwe │     12.7 │       1.9 │     5139 │  │
│ │ Name      │    │ 564727955 │          │ East,     │ an        │          │          │           │          │  │
│ │           │    │           │          │ North     │           │          │          │           │          │  │
│ │           │    │           │          │ Africa,   │           │          │          │           │          │  │
│ │           │    │           │          │ Afghanist │           │          │          │           │          │  │
│ │           │    │           │          │ an &      │           │          │          │           │          │  │
│ │           │    │           │          │ Pakistan  │           │          │          │           │          │  │
│ │           │    │           │          │ (excludin │           │          │          │           │          │  │
│ │           │    │           │          │ g high    │           │          │          │           │          │  │
│ │           │    │           │          │ income)   │           │          │          │           │          │  │
│ │ Country   │  5 │ 0.1876172 │ PAK      │ PAK       │ ABW       │ ZWE      │        3 │         1 │     2660 │  │
│ │ Code      │    │ 607879924 │          │           │           │          │          │           │          │  │
│ │           │    │         8 │          │           │           │          │          │           │          │  │
│ │ Time Code │  5 │ 0.1876172 │ YR2015   │ YR2015    │ YR2015    │ YR2024   │        6 │         1 │     2660 │  │
│ │           │    │ 607879924 │          │           │           │          │          │           │          │  │
│ │           │    │         8 │          │           │           │          │          │           │          │  │
│ └───────────┴────┴───────────┴──────────┴───────────┴───────────┴──────────┴──────────┴───────────┴──────────┘  │
╰────────────────────────────────────────────────────── End ──────────────────────────────────────────────────────╯

---

# 3

## Data Preprocessing

Here you can add sections like:

- Renaming columns
- Drop Redundant Columns
- Changing Data Types
- Dropping Duplicates
- Handling Missing Values
- Handling Unreasonable Data Ranges
- Feature Engineering / Transformation

Use `assert` where possible to show that preprocessing is done.

### Drop Columns

In [ ]:

# patterns that clearly mark gender-specific columns
gender_patterns = [
    r"\bfemale\b",
    r"\bmale\b",
    r"\bfe\b",
    r"\bma\b",
    r"\.FE\.",     # WDI code format
    r"\.MA\.",     # WDI code format
    r"_fe_",
    r"_ma_"
]

def is_gender_col(col):
    for p in gender_patterns:
        if re.search(p, col, flags=re.IGNORECASE):
            return True
    return False

# Keep only non-gender columns OR the total ones
cols_to_drop = [c for c in df.columns if is_gender_col(c), 'time_code']
df = df.drop(columns=cols_to_drop)

### Rename Columns

#### make columns snake case

In [30]:
# Rename columns to snake_case
df = clean_columns(df, replace={})

#### Shorten column names

In [32]:
rename_cols = {
    "country_name": "country",
    "country_code": "country_code",
    "time": "year",
    "time_code": "time_code",

    # unemployment
    "unemployment_with_advanced_education_%_of_total_labor_force_with_advanced_education_sl_uem_advn_zs":
        "unemp_adv_edu",
    "unemployment_with_basic_education_%_of_total_labor_force_with_basic_education_sl_uem_basc_zs":
        "unemp_basic_edu",
    "unemployment_with_intermediate_education_%_of_total_labor_force_with_intermediate_education_sl_uem_intm_zs":
        "unemp_intermediate_edu",
    "unemployment_total_%_of_total_labor_force_modeled_ilo_estimate_sl_uem_totl_zs":
        "unemp_total",
    "unemployment_youth_total_%_of_total_labor_force_ages_15_24_modeled_ilo_estimate_sl_uem_1524_zs":
        "unemp_youth",

    # education expenditure
    "current_education_expenditure_primary_%_of_total_expenditure_in_primary_public_institutions_se_xpd_cprm_zs":
        "exp_primary",
    "current_education_expenditure_secondary_%_of_total_expenditure_in_secondary_public_institutions_se_xpd_csec_zs":
        "exp_secondary",
    "current_education_expenditure_tertiary_%_of_total_expenditure_in_tertiary_public_institutions_se_xpd_cter_zs":
        "exp_tertiary",
    "current_education_expenditure_total_%_of_total_expenditure_in_public_institutions_se_xpd_ctot_zs":
        "exp_total",

    # attainment
    "educational_attainment_at_least_bachelors_or_equivalent_population_25_total_%_cumulative_se_ter_cuat_ba_zs":
        "attain_bachelors",
    "educational_attainment_at_least_completed_lower_secondary_population_25_total_%_cumulative_se_sec_cuat_lo_zs":
        "attain_lower_secondary",
    "educational_attainment_at_least_completed_post_secondary_population_25_total_%_cumulative_se_sec_cuat_po_zs":
        "attain_post_secondary",
    "educational_attainment_at_least_completed_primary_population_25_years_total_%_cumulative_se_prm_cuat_zs":
        "attain_primary",
    "educational_attainment_at_least_completed_short_cycle_tertiary_population_25_total_%_cumulative_se_ter_cuat_st_zs":
        "attain_short_tertiary",
    "educational_attainment_at_least_completed_upper_secondary_population_25_total_%_cumulative_se_sec_cuat_up_zs":
        "attain_upper_secondary",
    "educational_attainment_at_least_masters_or_equivalent_population_25_total_%_cumulative_se_ter_cuat_ms_zs":
        "attain_masters",
    "educational_attainment_doctoral_or_equivalent_population_25_total_%_cumulative_se_ter_cuat_do_zs":
        "attain_doctoral",

    # gov spending
    "expenditure_on_primary_education_%_of_government_expenditure_on_education_se_xpd_prim_zs":
        "gov_exp_primary",
    "expenditure_on_secondary_education_%_of_government_expenditure_on_education_se_xpd_seco_zs":
        "gov_exp_secondary",
    "expenditure_on_tertiary_education_%_of_government_expenditure_on_education_se_xpd_tert_zs":
        "gov_exp_tertiary",
    "government_expenditure_on_education_total_%_of_gdp_se_xpd_totl_gd_zs":
        "gov_exp_gdp",
    "government_expenditure_on_education_total_%_of_government_expenditure_se_xpd_totl_gb_zs":
        "gov_exp_total",

    # other
    "gross_intake_ratio_in_first_grade_of_primary_education_total_%_of_relevant_age_group_se_prm_gint_zs":
        "gross_intake_primary",
    "labor_force_with_advanced_education_%_of_total_working_age_population_with_advanced_education_sl_tlf_advn_zs":
        "labor_adv_edu",
    "labor_force_with_basic_education_%_of_total_working_age_population_with_basic_education_sl_tlf_basc_zs":
        "labor_basic_edu",
    "labor_force_with_intermediate_education_%_of_total_working_age_population_with_intermediate_education_sl_tlf_intm_zs":
        "labor_intermediate_edu",
    "share_of_youth_not_in_education_employment_or_training_total_%_of_youth_population_sl_uem_neet_zs":
        "neet_youth"
}

In [33]:
df = df.rename(columns=rename_cols)

In [ ]:
# print columns after renaming
df.columns.tolist()

### Change Data Types

In [ ]:
df.dtypes

In [ ]:
# convert country and code to categorical
df["country"] = df["country"].astype("category")
df["country_code"] = df["country_code"].astype("category")

# convert year to int
df["year"] = df["year"].astype("float").astype("Int64")   # handles missing years safely

# convert everything else/numeric cols to float
numeric_cols = df.columns.difference(["country", "country_code", "year"])
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors="coerce").astype("float")

### Dropping Duplicates

In [61]:
df = df.drop_duplicates(subset=["country", "year"], keep="first")

In [62]:
# Verify rows dropped
assert df.duplicated().sum()==0

### Handling Missing Values

In [ ]:
df.replace({'..': np.nan, '...': np.nan, 'N/A': np.nan, 'na': np.nan, 'NA': np.nan, '': np.nan}, inplace=True)

In [53]:

numeric_cols = df.select_dtypes(include="number").columns.tolist()
if 'year' in numeric_cols:
    numeric_cols.remove('year')

#### Forward/Backward Fill

In [ ]:

# forward/backward fill within each country 
df[numeric_cols] = df.groupby("country", group_keys=False)[numeric_cols].apply(
    lambda g: g.ffill().bfill()
)

#### Linear Interpolation

In [ ]:

# linear interpolation within each country 
for col in numeric_cols:
    df[col] = df.groupby("country")[col].transform(
        lambda s: s.interpolate(method="linear", limit_direction="both")
    )

#### Fill with Median

In [ ]:

# fill remaining missing values with country median 
for col in numeric_cols:
    df[col] = df[col].fillna(df.groupby("country")[col].transform("median"))

#### Fill with Global Median

In [ ]:

# global median if country has no data
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

In [ ]:

# final checks
missing_after = df[numeric_cols].isna().mean().sort_values(ascending=False) * 100
print("Missing % after pipeline (top):")
print(missing_after.head(20))

#### Fix country names to standard

In [63]:
df["country"] = df["country"].str.strip().str.title()

In [55]:

valid_countries = {
    'Afghanistan','Albania','Algeria','Andorra','Angola','Antigua and Barbuda','Argentina','Armenia',
    'Australia','Austria','Azerbaijan','Bahamas','Bahrain','Bangladesh','Barbados','Belarus','Belgium',
    'Belize','Benin','Bhutan','Bolivia','Bosnia and Herzegovina','Botswana','Brazil','Brunei Darussalam',
    'Bulgaria','Burkina Faso','Burundi','Cabo Verde','Cambodia','Cameroon','Canada','Central African Republic',
    'Chad','Chile','China','Colombia','Comoros','Congo','Democratic Republic of the Congo','Costa Rica','Croatia',
    'Cuba','Cyprus','Czech Republic','Czechia','Denmark','Djibouti','Dominica','Dominican Republic','Ecuador',
    'Egypt','El Salvador','Equatorial Guinea','Eritrea','Estonia','Eswatini','Ethiopia','Fiji','Finland','France',
    'Gabon','Gambia','Georgia','Germany','Ghana','Greece','Grenada','Guatemala','Guinea','Guinea-Bissau','Guyana',
    'Haiti','Honduras','Hungary','Iceland','India','Indonesia','Iran','Iraq','Ireland','Israel','Italy','Jamaica',
    'Japan','Jordan','Kazakhstan','Kenya','Kiribati','Kuwait','Kyrgyzstan','Lao PDR','Latvia','Lebanon','Lesotho',
    'Liberia','Libya','Liechtenstein','Lithuania','Luxembourg','Madagascar','Malawi','Malaysia','Maldives','Mali',
    'Malta','Marshall Islands','Mauritania','Mauritius','Mexico','Micronesia','Moldova','Monaco','Mongolia',
    'Montenegro','Morocco','Mozambique','Myanmar','Namibia','Nauru','Nepal','Netherlands','New Zealand','Nicaragua',
    'Niger','Nigeria','North Korea','North Macedonia','Norway','Oman','Pakistan','Palau','Panama',
    'Papua New Guinea','Paraguay','Peru','Philippines','Poland','Portugal','Qatar','Romania','Russia','Rwanda',
    'Saint Kitts and Nevis','Saint Lucia','Saint Vincent and the Grenadines','Samoa','San Marino',
    'Sao Tome and Principe','Saudi Arabia','Senegal','Serbia','Seychelles','Sierra Leone','Singapore','Slovakia',
    'Slovenia','Solomon Islands','Somalia','South Africa','South Korea','South Sudan','Spain','Sri Lanka','Sudan',
    'Suriname','Sweden','Switzerland','Syria','Taiwan','Tajikistan','Tanzania','Thailand','Timor-Leste','Togo',
    'Tonga','Trinidad and Tobago','Tunisia','Turkey','Turkmenistan','Tuvalu','Uganda','Ukraine','United Arab Emirates',
    'United Kingdom','United States','Uruguay','Uzbekistan','Vanuatu','Venezuela','Vietnam','Yemen','Zambia','Zimbabwe'
}


rename_map = {
    'Bahamas, The': 'Bahamas',
    'Bolivia (Plurinational State of)': 'Bolivia',
    'Congo, Dem. Rep.': 'Democratic Republic of the Congo',
    'Congo, Rep.': 'Congo',
    'Côte d’Ivoire': 'Ivory Coast',
    'Ivory Coast': 'Côte d’Ivoire',
    "Democratic People's Republic of Korea": 'North Korea',
    'Iran (Islamic Republic of)': 'Iran',
    'Iran, Islamic Rep.': 'Iran',
    'Egypt, Arab Rep.': 'Egypt',
    'Gambia, The': 'Gambia',
    'Hong Kong SAR, China': 'Hong Kong',    
    'Macao SAR, China': 'Macao',           
    'Micronesia, Fed. Sts.': 'Micronesia',
    'Myanmar': 'Myanmar',
    'Lao PDR': 'Laos',
    "Lao People's Democratic Republic": 'Laos',
    'Netherlands (Kingdom of the)': 'Netherlands',
    'Republic of Moldova': 'Moldova',
    'Russian Federation': 'Russia',
    'Serbia Montenegro': 'Serbia',
    'Slovak Republic': 'Slovakia',
    'Kyrgyz Republic': 'Kyrgyzstan',
    'Türkiye': 'Turkey',
    'Viet Nam': 'Vietnam',
    'Yemen Arab Republic': 'Yemen',
    "People's Democratic Republic of Yemen": 'Yemen',
}


remove_if_contains = [
    "income",
    "IDA",
    "IBRD",
    "small states",
    "Caribbean",
    "Europe",
    "East Asia",
    "Sub-Saharan",
    "North America",
    "Not classified",
    "Fragile",
    "post-demographic",
    "pre-demographic",
    "demographic dividend",
    "Middle East",
]

# Territories list
territories = {
    'Aruba','Curacao','Montserrat','Mayotte','New Caledonia','Reunion','Guadeloupe','French Guiana',
    'French Polynesia','Cook Islands','Niue','Tokelau','Saint Helena','St. Martin (French part)',
    'Saint Martin (French Part)','Saint Barthélemy','United States Virgin Islands','Virgin Islands (U.S.)',
    'Puerto Rico (US)','Northern Mariana Islands','Wallis and Futuna Islands','Gibraltar','Isle of Man',
    'Canary Islands','Azores Islands','Jersey, Channel Islands','Channel Islands'
}

In [56]:

def clean_country(x):
    if pd.isna(x):
        return None

    x = x.strip()

    # rename first
    if x in rename_map:
        x = rename_map[x]

    # remove regions/income groups
    for key in remove_if_contains:
        if key.lower() in x.lower():
            return None

    # drop territories
    if x in territories:
        return None

    # keep only valid ISO names
    if x not in valid_countries:
        return None

    return x

In [57]:
df["country"] = df["country"].apply(clean_country)
df = df[df["country"].notna()]

In [58]:

print("After cleaning:", df["country"].nunique())

After cleaning: 180

In [64]:
unique_countries = df["country"].dropna().unique()
unique_countries = sorted(unique_countries)

with open("unique_countries.txt", "w", encoding="utf-8") as f:
    for country in unique_countries:
        f.write(country + "\n")

Afghanistan
Albania
Algeria
Andorra
Angola
Antigua And Barbuda
Argentina
Armenia
Australia
Austria
Azerbaijan
Bahamas
Bahrain
Bangladesh
Barbados
Belarus
Belgium
Belize
Benin
Bhutan
Bolivia
Bosnia And Herzegovina
Botswana
Brazil
Brunei Darussalam
Bulgaria
Burkina Faso
Burundi
Cabo Verde
Cambodia
Cameroon
Canada
Central African Republic
Chad
Chile
China
Colombia
Comoros
Congo
Costa Rica
Croatia
Cuba
Cyprus
Czechia
Democratic Republic Of The Congo
Denmark
Djibouti
Dominica
Dominican Republic
Ecuador
Egypt
El Salvador
Equatorial Guinea
Eritrea
Estonia
Eswatini
Ethiopia
Fiji
Finland
France
Gabon
Gambia
Georgia
Germany
Ghana
Greece
Grenada
Guatemala
Guinea
Guinea-Bissau
Guyana
Haiti
Honduras
Hungary
Iceland
India
Indonesia
Iran
Iraq
Ireland
Israel
Italy
Jamaica
Japan
Jordan
Kazakhstan
Kenya
Kiribati
Kuwait
Kyrgyzstan
Latvia
Lebanon
Lesotho
Liberia
Libya
Liechtenstein
Lithuania
Luxembourg
Madagascar
Malawi
Malaysia
Maldives
Mali
Malta
Marshall Islands
Mauritania
Mauritius
Mexico
Micronesia
Moldova
Monaco
Mongolia
Montenegro
Morocco
Mozambique
Myanmar
Namibia
Nauru
Nepal
Netherlands
New Zealand
Nicaragua
Niger
Nigeria
North Macedonia
Norway
Oman
Pakistan
Palau
Panama
Papua New Guinea
Paraguay
Peru
Philippines
Poland
Portugal
Qatar
Romania
Russia
Rwanda
Samoa
San Marino
Sao Tome And Principe
Saudi Arabia
Senegal
Serbia
Seychelles
Sierra Leone
Singapore
Slovakia
Slovenia
Solomon Islands
South Africa
South Sudan
Spain
Sri Lanka
Sudan
Suriname
Sweden
Switzerland
Tajikistan
Tanzania
Thailand
Timor-Leste
Togo
Tonga
Tunisia
Turkmenistan
Tuvalu
Uganda
Ukraine
United Arab Emirates
United Kingdom
United States
Uruguay
Uzbekistan
Vanuatu
Vietnam
Zambia
Zimbabwe

### Z Score Scaling

In [66]:
scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

c:\Users\ThinkPad T480s\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\extmath.py:1144: RuntimeWarning: invalid value encountered in divide
  updated_mean = (last_sum + new_sum) / updated_sample_count
c:\Users\ThinkPad T480s\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\extmath.py:1149: RuntimeWarning: invalid value encountered in divide
  T = new_sum / new_sample_count
c:\Users\ThinkPad T480s\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\extmath.py:1169: RuntimeWarning: invalid value encountered in divide
  new_unnormalized_variance -= correction**2 / new_sample_count

### Feature Engineering / Transformation

---

# 4

## Data Visualization 
## Univariate Data Analysis

Here is where your analysis begins. You can add different sections based on your project goals.

### Histograms

In [32]:
# Code and visualization

**Observations**
- Ob 1
- Ob 2
- Ob 3

### Boxplots

## Bivariate

## Multivariate

### Scatterplot

### Heatmap

### Tree Diagrams

## Maps

---

# 5

## Conclusion

### Insights 
State the insights/outcomes of your project or notebook.

### Suggestions

Make suggestions based on insights.

### Recommendations
Areas to expand on:
- (if there is any)

---

# 6

## Epilogue

### References

This is how we use inline citation[<sup id="fn1-back">[1]</sup>](#fn1).

[<span id="fn1">1.</span>](#fn1-back) _Author (date)._ Title. Available at: https://website.com (Accessed: Date). 

> Use [https://www.citethisforme.com/](https://www.citethisforme.com/) to create citations.

### Versioning
Notebook and insights by (author).
- Version: 1.5.0
- Date: 2023-05-15

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=b689e16b-e36c-4f8c-b17a-b3e876352669' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>